#!/bin/zsh

function prompt_julian_setup() {

    function prompt_setcolor() {
        local text=$1
        local foreground=$2
        local background=$3

        if [ -n $background ]; then
            echo "%{$FG[$foreground]$BG[$background]%}$text%{$reset_color%}"
        else
            echo "%{$FG[$foreground]%}$text%{$reset_color%}"
        fi
    }
    
    function git_prompt_info() {
        local git_info=""

        inside_git=`git rev-parse --is-inside-work-tree 2>&1 > /dev/null`
        if [ $? = 0 ]; then
            git_info="(git)"

            current_branch=`git status -s -b | awk '{print $2;}' | head -n1`
            git_info="$git_info $current_branch"
        else
            git_info=""
        fi

        echo $git_info
    }

    function python_virtual_env() {

        local python_virtual_env_info=""

        if [ -n "${VIRTUAL_ENV}" ]; then;
            python_virtual_env_info=" (PyEnv: `basename $VIRTUAL_ENV`)"
        fi

        echo $python_virtual_env_info
    }

    SEG1_PROMPT='$(prompt_setcolor "┏" 226)'
    SEG1_PROMPT="$SEG1_PROMPT"'$(prompt_setcolor "[" 046)'
    SEG1_PROMPT="$SEG1_PROMPT"'$(prompt_setcolor "%*" 213)'
    SEG1_PROMPT="$SEG1_PROMPT"'$(prompt_setcolor "]" 046)'

    SEG1_PROMPT="$SEG1_PROMPT "'$(prompt_setcolor "%n" 046)'
    SEG1_PROMPT="$SEG1_PROMPT@"'$(prompt_setcolor "%M" 033)'
    SEG1_PROMPT="$SEG1_PROMPT: "'$(prompt_setcolor "$(git_prompt_info)" 046)'
    
    SEG1_PROMPT="$SEG1_PROMPT"'$(prompt_setcolor "$(python_virtual_env)" 142)'

    SEG2_PROMPT="$SEG1_PROMPT
"'$(prompt_setcolor "┃" 226)'
    SEG2_PROMPT="$SEG2_PROMPT "'$(prompt_setcolor "%~" 178)'

    SEG2_PROMPT="$SEG2_PROMPT
"'$(prompt_setcolor "┗" 226)'
    SEG2_PROMPT="$SEG2_PROMPT> "

    PROMPT=$SEG2_PROMPT
    
}


