#!/usr/bin/env zsh

#################################################################
# Main Custom zshrc
#################################################################

# expand variables in template scripts

ZSH_SETUP_ROOT=`pwd`
ZSH_CUSTOM_RC_TEMPLATE=$ZSH_SETUP_ROOT/julian_custom_zshrc.template
ZSH_CUSTOM_RC_FILE=$ZSH_SETUP_ROOT/julian_custom_zshrc

sed -e "s:<<<ZSH_SETUP_ROOT>>>:$ZSH_SETUP_ROOT:g" $ZSH_CUSTOM_RC_TEMPLATE > $ZSH_CUSTOM_RC_FILE

ZSH_BOOTSTRAP_TEMPLATE=$ZSH_SETUP_ROOT/bootstrap/bootstrap.zsh.template
ZSH_BOOTSTRAP_FILE=$ZSH_SETUP_ROOT/bootstrap/bootstrap.zsh

sed -e "s:<<<ZSH_SETUP_ROOT>>>:$ZSH_SETUP_ROOT:g" $ZSH_BOOTSTRAP_TEMPLATE > $ZSH_BOOTSTRAP_FILE


# check if zshrc already has custom setting include
grep "julian_custom_zshrc" ~/.zshrc > /dev/null
grep_status=$?


# add custom zshrc to user zshrc
if [ $grep_status = 1 ]; then
    # add include to end of user zshrc
    echo "" >> $HOME/.zshrc
    echo "# Custom zsh setup" >> $HOME/.zshrc 
    echo "source $ZSH_CUSTOM_RC_FILE" >> $HOME/.zshrc
    echo "" >> $HOME/.zshrc
fi

##################################################################
# Tmux configuration file
##################################################################

TMUX_CONF_TEMPLATE=$ZSH_SETUP_ROOT/tmux.conf.template

sed -e "" $TMUX_CONF_TEMPLATE > tmux.conf
rm -f ~/.tmux.conf
cp tmux.conf ~/.tmux.conf

##################################################################
# Git configuration
##################################################################

GIT_USER_CONFIG=$ZSH_SETUP_ROOT/gitconfig

if [ -f $HOME/.gitconfig ]; then
    echo "Removing old gitconfig from home directory"
    rm $HOME/.gitconfig
fi
echo "Linking gitconfig to home dir"
ln -s $GIT_USER_CONFIG $HOME/.gitconfig

echo "Done running setup"
exit 0

